version: "3"

services:

  wasabi-base:
    container_name: wasabi_base
    image: wasabi-base-${WASABI_PROFILE}:${WASABI_VERSION}
    build: 
      context: .
      dockerfile: wasabi-base.Dockerfile
      args:
        - WASABI_MAVEN_SETTINGS
        - WASABI_VERSION
        - WASABI_PROFILE

  wasabi-api:
    container_name: wasabi_api
    image: wasabi-api-${WASABI_PROFILE}:${WASABI_VERSION}
    build: 
      context: .
      dockerfile: wasabi-api.Dockerfile
      args:
        - WASABI_BASE_IMAGE=wasabi-base-${WASABI_PROFILE}:${WASABI_VERSION}
        - WASABI_PORT_API
        - WASABI_PORT_JMX
        - WASABI_PORT_DEBUG
        - WASABI_PROFILE
        - WASABI_VERSION
        - MYSQL_DATABASE
        - MYSQL_HOSTNAME
        - MYSQL_USER
        - MYSQL_PASSWORD
        - MYSQL_PORT
        - CASSANDRA_USER
        - CASSANDRA_PASSWORD
        - CASSANDRA_HOST
    ports:
      - "${WASABI_PORT_API}:${WASABI_PORT_API}"
      - "${WASABI_PORT_JMX}:${WASABI_PORT_JMX}"
      - "${WASABI_PORT_DEBUG}:${WASABI_PORT_DEBUG}"
    depends_on:
      - wasabi-base
      - mysql
      - cassandra

  wasabi-ui:
    container_name: wasabi_ui
    image: wasabi-ui-${WASABI_PROFILE}:${WASABI_VERSION}
    build: 
      context: .
      dockerfile: wasabi-ui.Dockerfile
      args:
        - WASABI_BASE_IMAGE=wasabi-base-${WASABI_PROFILE}:${WASABI_VERSION}
        - WASABI_API=http://localhost:${WASABI_PORT_API}/api/v1
        - WASABI_PORT_UI
        - WASABI_PROFILE
    command: ["grunt", "serve:dist"]
    ports:
      - "${WASABI_PORT_UI}:${WASABI_PORT_UI}"
    depends_on:
      - wasabi-base
      - wasabi-api

  mysql:
    image: mysql:5.6.42
    container_name: wasabi_mysql
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
    restart: always

  cassandra:
    image: cassandra:3.11.3
    container_name: wasabi_cassandra
    volumes:
      - cassandra-data:/var/lib/cassandra
    ports:
      - "${CASSANDRA_PORT}:${CASSANDRA_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "[ $$(nodetool statusgossip) = running ]"]
      interval: 30s
      timeout: 10s
      retries: 3

  cassandra-setup:
    image: cassandra-setup-${WASABI_VERSION}:3.11.3
    build: 
      context: .
      dockerfile: wasabi-cassandra.Dockerfile
      args:
        - CASSANDRA_HOST
        - CASSANDRA_PASSWORD
        - CASSANDRA_PORT
        - CASSANDRA_USER
        - WASABI_VERSION
    container_name: wasabi_cassandra_setup
    command: ["/wasabi/cassandra-setup.sh"]
    depends_on:
      - cassandra

volumes:
  mysql-data:
  cassandra-data:
